---
# Vagrant SSH connection settings
ansible_user: vagrant
ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
ansible_ssh_extra_args: "-o IdentitiesOnly=yes"

# Create users
user_config:
  - username: john
    name: "John Fitzgerald"
    sshkey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFrUN5FoGMaokynGF5rD6DssBxCC4GXn9AryzL8q6EPt"

k8s_admins:
  - john

# geerlingguy.security
security_sudoers_passwordless:
  - john